global:
  scrape_interval: 5s # 5 saniyede bir metrikleri çek

scrape_configs:
  # 1. Prometheus'un kendi metriklerini izle
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 2. Cartmetrikleri
  - job_name: 'cart-service'
    metrics_path: '/metrics' #  /metrics adresinden çek
    static_configs:
      - targets: ['cart-service:8080']

  # 3. Catalog metrikleri
  - job_name: 'catalog-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['catalog-service:8080']

  # 4. User metrikleri
  - job_name: 'user-service'
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'payment-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['payment-service:8080']